development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:782c461ee7bcf8533c023025dfcce06f@scat.redistogo.com:11855/
  channel_prefix: cacophony_app_production
